
library(tidyverse)

data.frame(
  recurso = c("Conectividad Terrestre Reporte","Conectividad Terrestre","Conectividad Aérea", "Turismo Internacional Reporte", "Ocupación Hotelera", "Áreas Protegidas Reporte", 
              "Áreas Protegidas Tablero","EVYTH", "Turismo Internacional Tablero",
              "PUNA", "MULC", "Empleo", "mapeAr", "Agencias", "SIG", "CRUCERISMO", "Conectividad Aérea Reporte",
              "Indicadores ODS","Índice Turístico","Últimos datos","Ocupación Hotelera Tablero"),
  src = c("img/conectividad-terrestre-reporte.png","img/conectividad-terrestre.png", "img/conectividad.png","img/ti.png", "img/eoh.png","img/parques.png",
          "img/parques_tablero.png","img/evyth.png","img/ti_dash.png" ,
          "img/puna.png", "img/mulc.png", "img/empleo.png", "img/mapeAr.png", "img/agencias.png", "img/visor.png",
          "img/crucerismo.png", "img/conectividad_aerea.png","img/indicadores_ods.png","img/indice.png","img/ultimos_datos.png", "img/eoh_tablero.png"),
  url = c("https://tableros.yvera.tur.ar/conectividad_terrestre.html", 
          "https://tableros.yvera.tur.ar/conectividad_terrestre/", 
          "https://tableros.yvera.tur.ar/conectividad/",
          "https://tableros.yvera.tur.ar/internacional.html",
          "https://tableros.yvera.tur.ar/eoh.html",
          "https://tableros.yvera.tur.ar/areas_protegidas.html",
          "https://tableros.yvera.tur.ar/tablero_areas_protegidas",
          "https://tableros.yvera.tur.ar/interno.html",
          "https://tableros.yvera.tur.ar/turismo_internacional/",
          "https://tableros.yvera.tur.ar/puna/",
          "https://tableros.yvera.tur.ar/mulc.html",
          "https://tableros.yvera.tur.ar/empleo.html",
          "https://tableros.yvera.tur.ar/mapeAr",
          "https://tableros.yvera.tur.ar/agencias", 
          "https://tableros.yvera.tur.ar/inversiones", 
          "https://tableros.yvera.tur.ar/crucerismo",
          "https://tableros.yvera.tur.ar/conectividad.html",
          "https://tableros.yvera.tur.ar/tablero_ODS",
          "https://tableros.yvera.tur.ar/indice_turistico",
          "https://tableros.yvera.tur.ar/tablero_ultimos_datos/",
          "https://tableros.yvera.tur.ar/tablero_eoh/"
  ),
  description  = c("Reporte con los últimos datos de servicios regulares interurbanos de buses",
                   "Tablero interactivo con información de servicios regulares interurbanos de buses y servicios de turismo",
                   "Tablero interactivo con información aerocomercial para el turismo",
                   "El reporte presenta la última información de turismo receptivo, emisivo y balanza turística
                   por todas las vías (aéreo, terrestre y fluvial / marítimo)",
                   "Presenta los últimos datos disponibles de la Encuesta de Ocupación Hotelera (EOH)",
                   "Información de visitas a Áreas Protegidas Nacionales y Provinciales",
                   "Tablero para la consulta de información de visitas a Áreas Protegidas Nacionales y Provinciales",
                   "Reporte de los últimos datos de Turismo Interno estimados por la Encuesta de Viajes y Turismo de los Hogares",
                   "Tablero para la consulta de datos desagregados de las estimaciones históricas de Turismo Internacional",
                   "Tablero para la consulta de estimaciones agregadas del Padrón Único Nacional de Alojamientos (PUNA)",
                   "Reporte sobre transacciones en divisas relacionadas al turismo en el Mercado de Cambios (BCRA)",
                   "Reporte sobre empleo registrado en las ramas características del turismo",
                   "Tablero para la generación de mapas con información georeferenciada de Turismo",
                   "Tablero con información del Registro de Agencias de Viajes de la Dirección Nacional de Agencias de Viajes",
                   "Visor de Información Geográfica de Turismo para Plataforma de Inversiones", 
                   "Tablero interactivo con información sobre el crucerismo en Argentina",
                   "Reporte mensual sobre los últimos datos del sector aerocomercial a partir de la información de la Administración Nacional de Aviación Civil",
                   "Tablero interactivo para el seguimiento de indicadores de turismo en Argentina relacionados con los Objetivos de Desarrollo Sostenible (ODS)",
                   "Tablero interactivo para la exploración del Índice Turístico de Localidades",
                   "Tablero interactivo con los últimos datos del turismo en Argentina",
                   "Tablero interactivo con datos históricos de la Encuesta de Ocupación Hotelera (EOH)"
  ),
  tags = c("Reporte","Tablero", "Tablero","Reporte","Reporte","Reporte","Tablero","Reporte","Tablero", "Tablero", "Reporte", 
           "Reporte", "Tablero", "Tablero", "Tablero", "Tablero", "Reporte", "Tablero","Tablero","Tablero","Tablero"),
  Todos = c(1,1, 1,1, 1,1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1,1,1,1,1),
  Tablero = c(0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,1,1,1,0,1,1,1,1),
  Reporte = c(1, 0, 0,1, 1, 1,0, 1, 0, 0, 1, 1, 0,0,0,0, 1,0,0,0,0)) %>%
  as_tibble() %>%
  arrange(match(recurso, c("Últimos datos",
                           "Turismo Internacional Tablero",
                           "Turismo Internacional Reporte",
                           "EVYTH",
                           "Ocupación Hotelera Tablero",
                           "Ocupación Hotelera",
                           "Áreas Protegidas Tablero",
                           "Áreas Protegidas Reporte",
                           "Conectividad Aérea", 
                           "Conectividad Aérea Reporte",
                           "Conectividad Terrestre",
                           "Conectividad Terrestre Reporte",
                           "CRUCERISMO", 
                           "PUNA",
                           "Empleo",
                           "MULC", 
                           "SIG",
                           "Índice Turístico",
                           "Indicadores ODS",
                           "mapeAr", 
                           "Agencias"))) %>% 
  mutate(orden = row_number()) %>%   # ORDENO POR TEMA Y NO POR TIPO DE RECURSO
#arrange(orden)  %>%
  filter(recurso != "Agencias") %>%
write_csv(here::here("content", "recursos.csv"))
